### ISSUE TITLE
Crash when present another view controller

### ISSUE THREAD

**Issue by wangbourne** [artemstepanenko/CrossNavigation#19]
In my view controller (inherit from CNViewController), I could present a view controller with a simple way of "[self presentViewController:navigationController animated:YES completion:nil]", but will crash when trying to class "[self dismissViewControllerAnimated:YES completion:nil]"

Error message: 
"[TGCameraNavigationController prepareForTransitionToDirection:interactive:]: unrecognized selector sent to instance 0x13cd350a0"

**Comment by artemstepanenko** [comment]
Thanks. I'll take a look.

**Comment by artemstepanenko** [comment]
@wangbourne , check the develop branch or make "pod update" to fix the mentioned problem.
