### ISSUE TITLE
Support for UITabBarController?

### ISSUE THREAD

**Issue by AFcgi** [artemstepanenko/CrossNavigation#25]
Is it possible to support the UITabBarController?

**Comment by artemstepanenko** [comment]
Yes, if somebody implements this :)
You may implement it yourself or wait a week or so until I do this for you.

In case you want to do this there're two ways: **fast** and **slow**. The **fast**est implementation would be to create a subclass of the **UITabBarController**, copy the sources from **CNViewController.m** in **CNTabBarController.m**. For more details, please, let me know.

**Comment by AFcgi** [comment]
Thanks for your reply. I think I need both variants. Now I create a prototype and check the usability of this implementation. Later I need the best solution to integrate this. In my use case I have an UITabBarController and every view controller inside is a CrossNavigation-ViewController. So please let me know any details.

**Comment by artemstepanenko** [comment]
I think, in the beginning I misunderstood what you actually need. So you don't want the whole tab bar controller to support features from CNViewController, right? Do you want to switch tabs interactively?

**Comment by AFcgi** [comment]
I have a UITabBarController as initial ViewController. I would like that the first item (view controller) of this UITabBarController is a CNViewController. I saw that you have a feature-branch for UINavigationController. So I need the a solution for full supported UITabBarController as the outside VC.

**Comment by artemstepanenko** [comment]
Ok, then it's what I thought of. I'll try to solve this today, but I'm not sure. Definitely I'll manage this by the end of the week. Is this fine with you?

**Comment by AFcgi** [comment]
Thanks, it's fine for me.

**Comment by artemstepanenko** [comment]
Please, check the [new release](https://github.com/artemstepanenko/CrossNavigation/releases/tag/v1.2.0). Let me know if you have any questions or issues.
